### PR TITLE
Change the variable name so that the passed parameters are correct

### LINKED ISSUE #13: The compiled code failed because the variable name was not changed
The compiled code returns the following error:
error: not found: value initPath
[ERROR]  logInfo(s"Intel Optane PMem initialized with path: ${initPath}, size: ${pmemInitialSize} ")

### PR DESCRIPTION
**Pull request by JustDoCoder**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

File: src/main/scala/org/apache/spark/storage/BlockManager.scala [hunk 1]
```diff
@@ -210,8 +210,8 @@ private[spark] class BlockManager(
       }
 
       require(file.isDirectory(), "PMem directory is required for initialization")
-      PersistentMemoryPlatform.initialize(initPath, pmemInitialSize, 0)
-      logInfo(s"Intel Optane PMem initialized with path: ${initPath}, size: ${pmemInitialSize} ")
+      PersistentMemoryPlatform.initialize(path_postfix, pmemInitialSize, 0)
```
Comment (winningsix) [inline src/main/scala/org/apache/spark/storage/BlockManager.scala]: ```file.getAbsolutePath``` ?

Comment (JustDoCoder) [reply src/main/scala/org/apache/spark/storage/BlockManager.scala]: @winningsix  Thanks for reminding, the absolute path of the object should be passed as a parameter

**Comment by yeyuqiang** [comment]
LGTM
